baseurl = "programiraj.ba/"
#title = "johndoe"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "programiraj-ba"

[params]
    author = "Mirza Abazovic"
    description = "My personal website"
    keywords = "blog,developer,personal"
    info = "Software engineer"
    avatarurl = "images/avatar.jpeg"
    #footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/MirzaAbazovic/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter"
#     weight = 3
#     url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/mirza-abazovic-063a7397/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@mirza.abazovic"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about/"
# [[menu.main]]
#     name = "Projects"
#     weight = 3
#     url = "/projects/"
# [[menu.main]]
#     name = "Contact me"
#     weight = 5
#     url = "/contact/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
       # title = "John Doe"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Mirza Abazovic"
        info = "Software Engineer"
        description = "Mirza Abazovic's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        # [[languages.en.menu.main]]
        # name = "About"
        # weight = 1.0
        # url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 1.0
        url = "https://blog.programiraj.ba"

        # [[languages.en.menu.main]]
        # name = "Projects"
        # weight = 3
        # url = "/projects/"
        # [[languages.en.menu.main]]
        # name = "Contact me"
        # weight = 5
        # url = "/contact/"


#     [languages.bs]
#         languagename = "Bosanski"
# #        title = "John Doe po polsku"


#         [languages.bs.params]
#             author = "Mirza Abazović"
#             description = "Privatna stranica Mirze Abazovića"
#             keywords = "blog,developer"
#             info = "Softver inžinjer"

#         [languages.bs.menu]

#             [[languages.bs.menu.main]]
#             name = "O meni"
#             weight = 1.0
#             url = "/bs/about/"

#             [[languages.bs.menu.main]]
#             name = "Blog"
#             weight = 2.0
#             url = "/bs/posts/"

#             # [[languages.bs.menu.main]]
#             # name = "projektowanie"
#             # weight = 3
#             # url = "/projektowanie/"
#             # [[languages.bs.menu.main]]
#             # name = "kontakt"
#             # weight = 5
#             # url = "/kontakt/"