version: 2.1
jobs:
  build-image:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
    - checkout
    - run:
        name: "Build doker image"
        command: cd deploy && docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg BUILD_VERSION=1.0.0 -t abazovic/hugo:1.0.0 -t abazovic/hugo:latest .
    - deploy:
        command: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push abazovic/hugo
  build-site:
    docker:
    - image: abazovic/hugo
    steps:
    - checkout
    - run:
        name: Run Hugo
        command: cd blog && HUGO_ENV=production hugo -v
    - run:
        name: Deploy Website
        command: deploy/deploy.sh
workflows:
  version: 2
  workflow:
    jobs:
    - build-image
    - build-site