version: 2.1
jobs:
  build-publish-site:
    docker:
    - image: abazovic/hugo
    steps:
    - checkout
    - run:
        name: Run Hugo
        command: cd blog && HUGO_ENV=production hugo -v
    - run:
        name: Deploy Website
        command: deploy/deploy.sh
workflows:
  version: 2
  workflow:
    jobs:
    - build-publish-site