version: 2.1
jobs:
  build-publish-site:
    docker:
    - image: abazovic/hugo:1.0.0
    steps:
    - checkout
    - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
    - run:
        name: "Run Hugo for blog"
        command: cd blog && HUGO_ENV=production hugo -v
    - run:
        name: "Run Hugo for homepage"
        command: cd home && HUGO_ENV=production hugo -v
    - run:
        name: "Deploy website"
        command: deploy/deploy.sh
workflows:
  version: 2
  workflow:
    jobs:
    - build-publish-site